### ISSUE TITLE
Conversion specs are incorrect

### ISSUE THREAD

**Issue by halostatue** [cozy-elixir/cozy_case#3]
The conversion function specs are basically:

```elixir
@spec snake_case(accepted_input_types()) :: String.t()
```

This is incorrect. There should probably be *three* specs:

```elixir
@spec snake_case(String.t() | atom()) :: String.t()
@spec snake_case(map()) :: map()
@spec snake_case(list()) :: list()
```

The latter might be able to be simplified as:

```elixir
@spec snake_case(String.t() | atom()) :: String.t()
@spec snake_case(a) :: a when a: map() | list()
```

It doesn't appear that dialyzer is seeing usage in the tests, but I am seeing warnings from the currently released version of `cozy_case` in my project.

**Comment by c4710n** [comment]
Thank you for this report. ❤️ 

It has been fixed, and will be released after another issue is resolved.
